services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_KEY: demo:value
      PORT: 3000
    depends_on:
      - redis
  redis:
    image: docker/dhi-redis:7
    volumes:
      - redis-data:/data
volumes:
  redis-data: